# Generated by Django 4.2.14 on 2025-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
