# Generated by Django 4.2.14 on 2025-01-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productmodel_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='is_admin',
            new_name='is_vendor',
        ),
    ]
