# Generated by Django 4.2.14 on 2024-10-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='slug',
        ),
    ]
