# Generated by Django 4.2.14 on 2024-10-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_model_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
